'use client';

import { AlertTriangle, Clock, MapPin, Navigation, Phone } from 'lucide-react';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { InputOTP, InputOTPGroup, InputOTPSlot } from '@/components/ui/input-otp';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { DriverAction, DriverRide } from '@/types/driver-ride';

interface ActiveTripSheetProps { ride: DriverRide | null; action: DriverAction; otp: string; pending: boolean; onOtpChange: (value: string) => void; onStatus: (status: 'ARRIVED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED') => void; onReturnToIdle: () => void; }
export function ActiveTripSheet({ ride, action, otp, pending, onOtpChange, onStatus, onReturnToIdle }: ActiveTripSheetProps) {
  if (!ride) return null;
  const primary = action.kind === 'MARK_ARRIVED' ? <Button className="min-h-11 w-full" disabled={pending} onClick={() => onStatus('ARRIVED')}>Mark arrived</Button> : action.kind === 'VERIFY_OTP' ? <div className="space-y-3"><InputOTP maxLength={4} value={otp} onChange={onOtpChange} containerClassName="justify-center"><InputOTPGroup className="border-2 border-border bg-background shadow-sm focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/30">{[0, 1, 2, 3].map((index) => <InputOTPSlot key={index} index={index} />)}</InputOTPGroup></InputOTP><Button className="min-h-11 w-full" disabled={pending || otp.length !== 4} onClick={() => onStatus('IN_PROGRESS')}>Verify OTP and start trip</Button></div> : action.kind === 'COMPLETE_TRIP' ? <Button className="min-h-11 w-full" disabled={pending} onClick={() => onStatus('COMPLETED')}>Complete trip</Button> : action.kind === 'RETURN_TO_IDLE' ? <Button className="min-h-11 w-full" onClick={onReturnToIdle}>Return to online</Button> : null;
  return <section className="fixed inset-x-0 bottom-0 z-30 mx-auto max-w-2xl rounded-t-2xl border border-border bg-popover/95 p-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] shadow-lg backdrop-blur"><div className="mx-auto mb-4 h-1 w-10 rounded-full bg-border" /><header className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Avatar><AvatarFallback>{ride.passengerName?.slice(0, 1) ?? 'R'}</AvatarFallback></Avatar><div><p className="font-display font-bold">{ride.passengerName ?? 'Rider'}</p><p className="flex items-center gap-1 text-xs text-muted-foreground"><Clock className="size-3" />{ride.status.replace('_', ' ')}</p></div></div><Badge variant="outline" className="tabular-nums">PKR {(ride.finalFare ?? ride.offeredFare).toLocaleString()}</Badge></header><div className="my-4 grid gap-2 border-y border-border py-4 text-sm"><p className="flex gap-2"><MapPin className="mt-0.5 size-4 shrink-0 text-emerald-500" />{ride.pickupAddress}</p><p className="flex gap-2"><Navigation className="mt-0.5 size-4 shrink-0 text-primary" />{ride.dropoffAddress}</p></div><div className="mb-4 flex items-center gap-2 text-xs text-muted-foreground" aria-live="polite"><span className="size-2 rounded-full bg-primary" />{action.label}</div>{primary}<div className="mt-3 flex gap-2"><Button variant="outline" size="sm" className="min-h-11 flex-1"><Phone />Contact rider</Button>{['ACCEPTED', 'ARRIVED'].includes(ride.status) && <AlertDialog><AlertDialogTrigger asChild><Button variant="outline" size="sm" className="min-h-11 flex-1 text-destructive"><AlertTriangle />Safety & cancel</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancel this ride?</AlertDialogTitle><AlertDialogDescription>This ends the current trip request. Use safety support if you need immediate help.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep ride</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={pending} onClick={() => onStatus('CANCELLED')}>Cancel ride</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div></section>;
}
