'use client';

import { useEffect, useState } from 'react';
import { Check, Clock, MapPin, Navigation, Star, UserRound, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export interface RideRequest { id: string; rideId?: string; passengerName?: string; passengerRating?: number; pickupAddress: string; dropoffAddress: string; fare: number; offeredFare?: number; distanceKm?: number; estimatedMins?: number; expiresInSeconds?: number; }
interface RideRequestToastProps { request: RideRequest; onAccept: (request: RideRequest) => void; onDecline: (requestId: string) => void; onCounterOffer: (request: RideRequest, counterFare: number) => void; pending?: boolean; }
export default function RideRequestToast({ request, onAccept, onDecline, onCounterOffer, pending = false }: RideRequestToastProps) {
  const expiresIn = request.expiresInSeconds ?? 120; const [timeLeft, setTimeLeft] = useState(expiresIn); const [counterOpen, setCounterOpen] = useState(false); const [counterFare, setCounterFare] = useState(String(Math.round(request.fare * 1.15)));
  useEffect(() => { setTimeLeft(expiresIn); setCounterFare(String(Math.round(request.fare * 1.15))); setCounterOpen(false); }, [expiresIn, request.id, request.fare]);
  useEffect(() => { if (timeLeft <= 0) { onDecline(request.rideId ?? request.id); return; } const timer = window.setTimeout(() => setTimeLeft((value) => value - 1), 1000); return () => window.clearTimeout(timer); }, [onDecline, request.id, request.rideId, timeLeft]);
  const counter = Number(counterFare);
  return <aside className="w-full max-w-sm overflow-hidden rounded-xl border border-border bg-popover/95 text-popover-foreground shadow-lg backdrop-blur" aria-live="assertive"><div className="h-1 bg-muted"><div className="h-full bg-primary transition-[width] duration-1000" style={{ width: `${Math.max(0, (timeLeft / expiresIn) * 100)}%` }} /></div><div className="space-y-4 p-4"><header className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-full bg-primary/15 text-primary"><UserRound className="size-4" /></span><div><p className="font-display text-sm font-bold">{request.passengerName ?? 'Rider'}</p><p className="flex items-center gap-1 text-xs text-muted-foreground"><Star className="size-3 fill-primary text-primary" />{(request.passengerRating ?? 4.8).toFixed(1)} · New request</p></div></div><div className="text-right"><p className="font-display text-lg font-bold tabular-nums">PKR {request.fare.toLocaleString()}</p><p className="flex items-center justify-end gap-1 text-xs text-muted-foreground"><Clock className="size-3" />{timeLeft}s</p></div></header><div className="space-y-3 rounded-lg border border-border bg-muted/40 p-3 text-sm"><p className="flex gap-2"><MapPin className="mt-0.5 size-4 shrink-0 text-emerald-500" /><span><span className="block text-xs text-muted-foreground">Pickup</span>{request.pickupAddress}</span></p><p className="flex gap-2"><Navigation className="mt-0.5 size-4 shrink-0 text-primary" /><span><span className="block text-xs text-muted-foreground">Drop-off</span>{request.dropoffAddress}</span></p><p className="border-t border-border pt-2 text-xs text-muted-foreground tabular-nums">{request.distanceKm?.toFixed(1) ?? '—'} km · {request.estimatedMins ?? '—'} min</p></div>{counterOpen && <div className="flex gap-2"><Input className="border-2 border-border bg-background focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/30" inputMode="decimal" aria-label="Counter offer in PKR" value={counterFare} onChange={(event) => setCounterFare(event.target.value)} /><Button variant="secondary" disabled={pending || !Number.isFinite(counter) || counter <= 0} onClick={() => onCounterOffer(request, counter)}>Send</Button></div>}<div className="grid grid-cols-3 gap-2"><Button variant="outline" className="min-h-11" disabled={pending} onClick={() => onDecline(request.rideId ?? request.id)}><X />Reject</Button><Button variant="secondary" className="min-h-11" disabled={pending} onClick={() => setCounterOpen((open) => !open)}>Counter</Button><Button className="min-h-11" disabled={pending} onClick={() => onAccept(request)}><Check />Accept</Button></div></div></aside>;
}
