events {

}

http {
    upstream gateway {
        server gateway:5000;
    }

    # Redirect HTTP traffic to HTTPS & Handle Certbot ACME Challenges
    server {
        listen 80;
        server_name simpleride-api.duckdns.org;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # HTTPS Server Block
    server {
        listen 443 ssl;
        server_name simpleride-api.duckdns.org;

        ssl_certificate /etc/letsencrypt/live/simpleride-api.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/simpleride-api.duckdns.org/privkey.pem;

        location / {
            proxy_pass http://gateway;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        location /test {
            return 200 "This is Nginx Baby with SSL!";
        }
    }
}
